theme: jekyll-theme-minimal
title: API Client Boilerplate Rust
description: A repository template for API clients written in Rust
logo: https://raw.githubusercontent.com/guibranco/apiclient-boilerplate-rs/main/logo.png
show_downloads: true
