theme: jekyll-theme-minimal
title: API Client Boilerplate Rust SDK
description: A repository template for RUST API client projects
logo: https://raw.githubusercontent.com/GuilhermeStracini/apiclient-boilerplate-rs/main/logo.png
show_downloads: true
