os:
  - Visual Studio 2022

environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
      BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
    - TARGET: i686-pc-windows-msvc
      BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64

install:
  # If a newer build is queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose, but it is problematic because it tends to cancel builds pushed
  # directly to main/master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
          https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
          Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
            throw "There are newer queued builds for this pull request, failing early." }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain=stable-%TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build

deploy:

- provider: GitHub
  on:
   branch: main
  tag: v$(appveyor_build_version)
  description: Release v$(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  force_update: true
