name: Clippy check

on:
  workflow_dispatch:
  pull_request:

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Rustup add Clippy
        run: rustup component add clippy
      
      - name: Run linter
        uses: clechasseur/rs-clippy-check@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
